// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

#include "Service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace clang {
namespace clangd {
namespace remote {
namespace v1 {
}  // namespace v1
}  // namespace remote
}  // namespace clangd
}  // namespace clang
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_Service_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Service_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Service_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Service_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Service_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rService.proto\022\026clang.clangd.remote.v1\032"
  "\013Index.proto2\351\002\n\013SymbolIndex\022R\n\006Lookup\022\""
  ".clang.clangd.remote.LookupRequest\032 .cla"
  "ng.clangd.remote.LookupReply\"\0000\001\022[\n\tFuzz"
  "yFind\022%.clang.clangd.remote.FuzzyFindReq"
  "uest\032#.clang.clangd.remote.FuzzyFindRepl"
  "y\"\0000\001\022L\n\004Refs\022 .clang.clangd.remote.Refs"
  "Request\032\036.clang.clangd.remote.RefsReply\""
  "\0000\001\022[\n\tRelations\022%.clang.clangd.remote.R"
  "elationsRequest\032#.clang.clangd.remote.Re"
  "lationsReply\"\0000\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Service_2eproto_deps[1] = {
  &::descriptor_table_Index_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Service_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Service_2eproto = {
  false, false, 416, descriptor_table_protodef_Service_2eproto, "Service.proto", 
  &descriptor_table_Service_2eproto_once, descriptor_table_Service_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_Service_2eproto::offsets,
  file_level_metadata_Service_2eproto, file_level_enum_descriptors_Service_2eproto, file_level_service_descriptors_Service_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_Service_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Service_2eproto);
  return descriptor_table_Service_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Service_2eproto(&descriptor_table_Service_2eproto);
namespace clang {
namespace clangd {
namespace remote {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace remote
}  // namespace clangd
}  // namespace clang
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
